In \[1\]:

    import numpy as np

In \[2\]:

    arr = np.zeros(10)

In \[3\]:

    arr

Out\[3\]:

    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In \[4\]:

    arr = np.ones(10)

In \[5\]:

    arr

Out\[5\]:

    array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In \[9\]:

    arr = np.arange(10,50)

In \[10\]:

    arr

Out\[10\]:

    array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
           27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
           44, 45, 46, 47, 48, 49])

In \[19\]:

    arr = np.ones(10)*5

In \[20\]:

    arr

Out\[20\]:

    array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In \[21\]:

    arr = np.arange(10,50,2)

In \[22\]:

    arr

Out\[22\]:

    array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
           44, 46, 48])

In \[23\]:

    list = ([0,1,2],[3,4,5],[6,7,8])

In \[24\]:

    list

Out\[24\]:

    ([0, 1, 2], [3, 4, 5], [6, 7, 8])

In \[25\]:

    arr = np.array(list)

In \[26\]:

    arr

Out\[26\]:

    array([[0, 1, 2],
           [3, 4, 5],
           [6, 7, 8]])

In \[33\]:

    list = ([1,0,0],[0,1,0],[0,0,1])

In \[34\]:

    arr = np.array(list)

In \[35\]:

    arr

Out\[35\]:

    array([[1, 0, 0],
           [0, 1, 0],
           [0, 0, 1]])

In \[36\]:

    arr = np.identity(3)

In \[37\]:

    arr

Out\[37\]:

    array([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]])

In \[38\]:

    rand = np.random.rand(1)

In \[39\]:

    rand

Out\[39\]:

    array([0.95472551])

In \[40\]:

    rand = np.random.rand(25)

In \[41\]:

    rand

Out\[41\]:

    array([0.42169175, 0.95703784, 0.23028568, 0.07388202, 0.37372117,
           0.50755746, 0.08711717, 0.10365916, 0.78568544, 0.63964582,
           0.96173569, 0.70269729, 0.28730161, 0.32822982, 0.77993293,
           0.93145035, 0.43474299, 0.69315422, 0.43923201, 0.67648476,
           0.08224491, 0.29834879, 0.96809232, 0.81555152, 0.82201505])

In \[48\]:

    rand = np.random.rand(20)

In \[49\]:

    rand

Out\[49\]:

    array([0.83743558, 0.55498386, 0.0225916 , 0.66963369, 0.61982287,
           0.94643394, 0.10298032, 0.84351853, 0.61951631, 0.86325938,
           0.37922121, 0.84877258, 0.51009549, 0.89176356, 0.52052113,
           0.90231207, 0.71852961, 0.86045061, 0.67712243, 0.27315379])

In \[50\]:

    mat = np.arange(1,26).reshape(5,5)
    mat

Out\[50\]:

    array([[ 1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10],
           [11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25]])

In \[59\]:

    list = ([12,13,14,15],[17,18,19,20],[22,23,24,25])

In \[60\]:

    arr = np.array(list)

In \[61\]:

    arr

Out\[61\]:

    array([[12, 13, 14, 15],
           [17, 18, 19, 20],
           [22, 23, 24, 25]])

In \[66\]:

    arr[1][3]

Out\[66\]:

    20

In \[71\]:

    mat = np.arange(16,26).reshape(2,5)

mat

In \[72\]:

    mat

Out\[72\]:

    array([[16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25]])

In \[73\]:

    list = ([2,7,12,17,22])

In \[84\]:

    arr = np.array(list ).reshape(5,1)

In \[85\]:

    arr

Out\[85\]:

    array([[ 2],
           [ 7],
           [12],
           [17],
           [22]])

In \[91\]:

    arr = np.arange(21,26)

In \[92\]:

    arr

Out\[92\]:

    array([21, 22, 23, 24, 25])